/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Dialogs.CustomConfirmBox;
import Dialogs.CustomSuccessBox;
import Dialogs.CustomDialogBox;
import Connection.DBConnection;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class AdicionarQuestao extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPage
     */
    public AdicionarQuestao() {
        initComponents();
        try{
            Connection con = DBConnection.getConnection();
            Statement pst = con.createStatement();
            ResultSet rs = pst.executeQuery("SELECT ID FROM QUESTOES");

            int id = 0;
            int teste = 0;
            while(rs.next()){
                teste = rs.getInt(1);
                id = id + 1;
                if (teste == 10 & id == 2){
                    id = id - 1;
                    continue;
                }
                if (teste != id)
                    break;
            }
            if (teste == id)
                id = id + 1;
            label_id.setText(String.valueOf(id));
                
            
            rs = pst.executeQuery("SELECT count(ID) FROM QUESTOES");
            if(rs.next() & rs.getInt(1) == 10){
                label_questao.setEditable(false);
                label_a.setEditable(false);
                label_b.setEditable(false);
                label_c.setEditable(false);
                label_d.setEditable(false);
                label_resposta.setEditable(false);
                salvar.setEnabled(false);
                limpar.setEnabled(false);
                idDaQuestao.setEnabled(false);
                label_id.setEnabled(false);
                erro.setText("O Quiz já contém 10 exercícios.");

            }
        
        }catch(Exception e){
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, e);
        }
    }

    public boolean validateLength(){
        if(label_questao.getText().equals("") || label_a.getText().equals("") || label_b.getText().equals("") || label_c.getText().equals("") || label_d.getText().equals("") || label_resposta.getText().equals(""))
        {
            CustomDialogBox ccb = new CustomDialogBox("Todos os campos são obrigatórios.");
            ccb.setVisible(true);
            return false;
        }
            
        if(label_questao.getText().length() > 100){
            CustomDialogBox ccb = new CustomDialogBox("A pergunta não pode conter mais de 100 caracteres.");
            ccb.setVisible(true);
            return false;
        }
        if(label_a.getText().length() > 70){
            CustomDialogBox ccb = new CustomDialogBox("A alternativa (A) não pode conter mais de 70 caracteres.");
            ccb.setVisible(true);
            return false;
        }
        if(label_b.getText().length() > 70){
            CustomDialogBox ccb = new CustomDialogBox("A alternativa (B) não pode conter mais de 70 caracteres.");
            ccb.setVisible(true);
            return false;
        }
        if(label_c.getText().length() > 70){
            CustomDialogBox ccb = new CustomDialogBox("A alternativa (C) não pode conter mais de 70 caracteres.");
            ccb.setVisible(true);
            return false;
        }
        if(label_d.getText().length() > 70){
            CustomDialogBox ccb = new CustomDialogBox("A alternativa (D) não pode conter mais de 70 caracteres.");
            ccb.setVisible(true);
            return false;
        }
        if(label_resposta.getText().length() > 70){
            CustomDialogBox ccb = new CustomDialogBox("A Resposta não pode conter mais de 70 caracteres.");
            ccb.setVisible(true);
            return false;
        }
        if(label_resposta.getText().equals(label_a.getText()) || label_resposta.getText().equals(label_b.getText()) || label_resposta.getText().equals(label_c.getText()) || label_resposta.getText().equals(label_d.getText())){
        } else {
            CustomDialogBox ccb = new CustomDialogBox("Coloque a resposta igual a ao menos uma das alternativas.");
            ccb.setVisible(true);
            return false;
        }
           return true; 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        erro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idDaQuestao = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        label_questao = new javax.swing.JTextField();
        label_a = new javax.swing.JTextField();
        label_b = new javax.swing.JTextField();
        label_c = new javax.swing.JTextField();
        label_d = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        label_resposta = new javax.swing.JTextField();
        salvar = new rojerusan.RSButtonHover();
        limpar = new rojerusan.RSButtonHover();
        jLabel13 = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(34, 57, 121));
        kGradientPanel1.setkGradientFocus(100);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 102, 204));
        kGradientPanel1.setkTransparentControls(false);
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        kGradientPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 100, 10));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("USCS");
        kGradientPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 50));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 830));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(34, 57, 121));
        jLabel6.setText("uma nova Questão");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 370, -1));

        erro.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        erro.setForeground(new java.awt.Color(204, 0, 51));
        jPanel1.add(erro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 680, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel2.setText("Resposta correta:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 650, -1, -1));

        idDaQuestao.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        idDaQuestao.setText("ID da questão:");
        jPanel1.add(idDaQuestao, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel5.setText("Questão:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel7.setText("Opção A:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel10.setText("Opção B:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel11.setText("Opção C:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));

        label_questao.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label_questao.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 204)));
        label_questao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_questaoActionPerformed(evt);
            }
        });
        jPanel1.add(label_questao, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 1020, 40));

        label_a.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label_a.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 204)));
        jPanel1.add(label_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 1020, 40));

        label_b.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label_b.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 204)));
        jPanel1.add(label_b, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 1020, 40));

        label_c.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label_c.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 204)));
        jPanel1.add(label_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 1020, 40));

        label_d.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label_d.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 204)));
        jPanel1.add(label_d, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 1020, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel12.setText("Opção D:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 560, -1, -1));

        label_resposta.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        label_resposta.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 102, 204)));
        jPanel1.add(label_resposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, 920, 40));

        salvar.setBorder(null);
        salvar.setText("Salvar");
        salvar.setColorHover(new java.awt.Color(34, 57, 121));
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        jPanel1.add(salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 740, -1, -1));

        limpar.setBackground(new java.awt.Color(255, 255, 255));
        limpar.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 153, 102)));
        limpar.setText("Limpar");
        limpar.setColorHover(new java.awt.Color(255, 153, 102));
        limpar.setColorText(new java.awt.Color(255, 153, 102));
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });
        jPanel1.add(limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 740, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 153, 102));
        jLabel13.setText("CRIAR");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 150, -1));

        label_id.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        label_id.setForeground(new java.awt.Color(255, 153, 102));
        label_id.setText("0");
        jPanel1.add(label_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        close.setFont(new java.awt.Font("SansSerif", 0, 25)); // NOI18N
        close.setForeground(new java.awt.Color(153, 153, 153));
        close.setText("X");
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 10, 20, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        jLabel14.setText(" Voltar");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 760, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 830));

        setSize(new java.awt.Dimension(1523, 824));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void label_questaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_questaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_label_questaoActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        label_questao.setText("");
        label_a.setText("");
        label_b.setText("");
        label_c.setText("");
        label_d.setText("");
        label_resposta.setText("");
    }//GEN-LAST:event_limparActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        if(validateLength())
        {
            String id = label_id.getText();
            String name = label_questao.getText();
            String opt1 = label_a.getText();
            String opt2 = label_b.getText();
            String opt3 = label_c.getText();
            String opt4 = label_d.getText();
            String answer = label_resposta.getText();
        try{
            Connection con = DBConnection.getConnection();
            PreparedStatement pst = con.prepareStatement("INSERT INTO QUESTOES VALUES(?,?,?,?,?,?,?)");
            pst.setString(1, id);
            pst.setString(2, name);
            pst.setString(3, opt1);
            pst.setString(4, opt2);
            pst.setString(5, opt3);
            pst.setString(6, opt4);
            pst.setString(7, answer);
            pst.executeUpdate();
            
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            CustomSuccessBox csb = new CustomSuccessBox("Exercício criado com Sucesso.");
            csb.setVisible(true);
            this.dispose();
        }catch(Exception e){
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, e);
        }
        }
        
    }//GEN-LAST:event_salvarActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        CustomConfirmBox ccb = new CustomConfirmBox("Você deseja fechar o programa?", this);
        ccb.setVisible(true);
    }//GEN-LAST:event_closeMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        GerenciarPage gp = new GerenciarPage();
        gp.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdicionarQuestao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JLabel erro;
    private javax.swing.JLabel idDaQuestao;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField label_a;
    private javax.swing.JTextField label_b;
    private javax.swing.JTextField label_c;
    private javax.swing.JTextField label_d;
    private javax.swing.JLabel label_id;
    private javax.swing.JTextField label_questao;
    private javax.swing.JTextField label_resposta;
    private rojerusan.RSButtonHover limpar;
    private rojerusan.RSButtonHover salvar;
    // End of variables declaration//GEN-END:variables
}

